name: CalmDown
options:
  bundleIdPrefix: com.calmdown
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true
  transitivelyLinkDependencies: true

packages: {}

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_BITCODE: "NO"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    GCC_OPTIMIZATION_LEVEL: "0"

targets:

  CalmDown:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: CalmDown
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.calmdown.app
        INFOPLIST_FILE: CalmDown/Info.plist
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: CalmDown/CalmDown.entitlements
    dependencies:
      - target: CalmDownWidgets
        embed: true

  CalmDownWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: CalmDownWatch
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.calmdown.app.watchkitapp
        INFOPLIST_FILE: CalmDownWatch/Info.plist
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"

  CalmDownWidgets:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: CalmDownWidgets
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.calmdown.app.widgets
        INFOPLIST_FILE: CalmDownWidgets/Info.plist
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        APPLICATION_EXTENSION_API_ONLY: "YES"
